/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package u05_javahelp;

import java.io.File;
import java.net.URL;
import javax.help.HelpBroker;
import javax.help.HelpSet;
import javax.swing.JOptionPane;

/**
 * Clase principal que representa la interfaz gráfica de usuario (GUI). Gestiona
 * la ventana principal de la aplicación, integrando el sistema de ayuda
 * JavaHelp y la lógica de navegación del proyecto DevSoft.
 *
 * @author Antonio Naranjo Castillo
 * @version 1.0
 */
public class FormularioPrincipal extends javax.swing.JFrame {

    /**
     * Constructor de la clase. Inicializa los componentes de la interfaz
     * gráfica y configura el sistema de ayuda JavaHelp vinculando el archivo
     * HelpSet con la pulsación de la tecla F1 y los botones de ayuda
     * correspondientes.
     */
    public FormularioPrincipal() {
        // Se inician los componentes de la interfaz
        initComponents();
        // Se da una pausa al hilo principal de 2 segundos para que se vea la imagen splash
        try {
            Thread.sleep(2000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        // Se muestra la ventana (y se cerrará el splah)
        this.setVisible(true);
        // Centrar la ventana JFrame en la pantalla
        this.setLocationRelativeTo(null);
        // Iniciar el foco sobre la ventana principal
        this.getContentPane().setFocusable(true);
        // Se llama al método obtener ayuda
        obtenerAyuda();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        txtNombreProyecto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonSalir = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuItemAyudaGeneral = new javax.swing.JMenuItem();
        menuItemCrearProyecto = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setForeground(java.awt.Color.blue);
        jLabel1.setText("Nombre del proyecto:");

        txtNombreProyecto.setToolTipText("Nombre del proyecto");

        jLabel2.setText("Pulsa F1 en la ventana para ver \"Ayuda General\"");

        jLabel3.setText("Pulsa F1 dentro del campo para ver \"Crear Proyecto\"");

        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        jMenu1.setText("Archivo");

        jMenuSalir.setText("Salir");
        jMenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSalirActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ayuda");

        menuItemAyudaGeneral.setText("Ayuda General");
        jMenu2.add(menuItemAyudaGeneral);

        menuItemCrearProyecto.setText("Crear Proyecto");
        jMenu2.add(menuItemCrearProyecto);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtNombreProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombreProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jButtonSalir)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Gestiona el evento de pulsación sobre el botón de salida. Finaliza la
     * aplicación y cierra de forma segura todos los recursos de la aplicación.
     *
     * @param evt Objeto de evento que contiene los datos del clic realizado.
     */
    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        confirmarSalida();
    }//GEN-LAST:event_jButtonSalirActionPerformed

    /**
     * Gestiona el evento de selección de la opción "Salir" en la barra de menú.
     * Proporciona una vía alternativa de cierre de la aplicación.
     *
     * @param evt Objeto de evento con la información de la selección del menú.
     */
    private void jMenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSalirActionPerformed
        // TODO add your handling code here:
        confirmarSalida();
    }//GEN-LAST:event_jMenuSalirActionPerformed

    /**
     * Gestiona el evento de clic de ratón sobre el área de la ventana principal
     * de la interfaz. Este método se dispara cuando el usuario hace clic en
     * cualquier zona libre del contenedor principal, permitiendo definir
     * comportamientos específicos de interacción con la interfaz.
     *
     * @param evt Objeto MouseEvent que contiene información sobre la posición
     * del puntero del ratón y tras pulsar el botón izquierdo del mismo.
     */
    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        // La ventana principal recupera el foco al hacer clic sobre ella
        getContentPane().requestFocusInWindow();
    }//GEN-LAST:event_formMouseClicked

    /**
     * Carga y configura el sistema de ayuda JavaHelp de la aplicación. Este
     * método localiza el archivo HelpSet (HS), crea el componente HelpBroker y
     * vincula la ayuda con los distintos elementos de la interfaz, permitiendo
     * la activación de la ayuda mediante la tecla F1 y botones específicos.
     */
    public void obtenerAyuda() {

        try {

            // 1. Localizar el archivo HelpSet (.hs)
            File fichero = new File("helpDS_ANC" + File.separator + "help_set.hs");
            URL hsURL = fichero.toURI().toURL();

            // 2. Crear el HelpSet y el HelpBroker
            HelpSet helpset = new HelpSet(getClass().getClassLoader(), hsURL);
            HelpBroker hb = helpset.createHelpBroker();

            // 3. ASIGNACIÓN GENERAL (F1 en la ventana principal)
            // 'this' hace referencia al JFrame principal
            hb.enableHelpKey(this.getContentPane(), "ayuda_general", helpset);

            // Vincular también al ítem de menú "Ayuda General"
            hb.enableHelpOnButton(menuItemAyudaGeneral, "ayuda_general", helpset);

            // 4. AYUDA CONTEXTUAL (F1 dentro del campo de texto)
            // Cuando el foco esté en el JTextField del nombre, F1 mostrará la ayuda de creación
            hb.enableHelpKey(txtNombreProyecto, "ayuda_crear", helpset);

            // Vincular al ítem de menú "Crear Proyecto"
            hb.enableHelpOnButton(menuItemCrearProyecto, "ayuda_crear", helpset);

        } catch (Exception e) {

            System.err.println("Error al cargar la ayuda: " + e.getMessage());

        }

    }

    /**
     * Muestra un cuadro de diálogo de confirmación antes de cerrar la
     * aplicación. Utiliza un JOptionPane para solicitar al usuario que confirme
     * su intención de salir. Si la respuesta es afirmativa, se procede al
     * cierre controlado del aplicativo.
     */
    private void confirmarSalida() {
        // Se definen los textos
        String mensaje = "¿Seguro que desea salir de la aplicación?";
        String titulo = "Confirmación de salida del programa";

        int respuesta = JOptionPane.showConfirmDialog(
                this,
                mensaje,
                titulo,
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
        );

        if (respuesta == JOptionPane.YES_OPTION) {
            System.exit(0);
        } else {
            // Se vuelve a la ventana principal
            // Se limpia el campo de texto
            txtNombreProyecto.setText("");
            // Se devuelve el foco a la ventana principal
            getContentPane().requestFocusInWindow();
        }
    }

    /**
     * Punto de entrada principal de la aplicación. Configura el entorno de
     * ejecución, establece el aspecto visual del sistema operativo y lanza la
     * interfaz gráfica.
     *
     * @param args Argumentos de la línea de comandos.
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuSalir;
    private javax.swing.JMenuItem menuItemAyudaGeneral;
    private javax.swing.JMenuItem menuItemCrearProyecto;
    private javax.swing.JTextField txtNombreProyecto;
    // End of variables declaration//GEN-END:variables
}
